import type pool from './db';

const seeds = [
  {
    id: 'seed-1',
    createdAt: new Date(Date.now() - 86400000 * 62),
    status: 'published',
    role: 'Postdoctoral Researcher',
    institutionType: 'Russell Group University',
    discipline: 'Chemistry',
    region: 'South East',
    timeWindow: '1–6 months ago',
    whatHappened: 'I returned to the lab after a weekend to find that a key piece of equipment — a rotary evaporator I had been using daily for three months — had vanished from the bench. There was no note, no email, no ticket raised. I immediately assumed it had been stolen, filed an incident report with security, and spent two days retracing where it could have gone. It turned out that the facilities team had removed it for a scheduled PAT test. The test took four working days. Nobody had informed me, the lab manager, or the PI.',
    impact: 'Two days were lost to the theft investigation. A further four days of experiments were delayed. My PhD student missed a group meeting deadline. The stress of believing equipment worth over £8,000 had been stolen was significant.',
    improvement: 'Facilities teams should leave a notice on removed equipment and send a 48-hour advance email to the lab contact.',
    consentPublish: true,
    publishTitle: 'Equipment Removed Without Notice Triggers False Theft Report',
    publishSummary: 'A researcher returned after the weekend to find a critical piece of lab equipment missing with no explanation, triggering a security incident report before discovering it had been taken for routine electrical testing.',
    publishStory: '### What happened\nA researcher returned to their laboratory after a weekend break to find that a key piece of equipment had been removed from its assigned position. No note had been left, no email had been sent. Believing the equipment had been stolen, the researcher filed a formal security incident report and spent two working days investigating. The equipment had been removed by the facilities team for a scheduled portable appliance test.\n\n### Impact\nThe false alarm consumed two full working days and caused significant stress. Dependent experimental work was delayed by four days, causing a PhD student to miss a progress deadline.\n\n### What would help\nFacilities teams should leave a physical notice at the point of removal and send advance notification to the laboratory contact. A shared calendar of planned equipment interventions would allow researchers to reschedule around them.',
    anonymisationNotes: JSON.stringify(['Equipment type generalised', 'Building and floor references removed']),
    riskFlags: JSON.stringify([]),
    confidence: 'high',
    publishedAt: new Date(Date.now() - 86400000 * 58),
  },
  {
    id: 'seed-2',
    createdAt: new Date(Date.now() - 86400000 * 54),
    status: 'published',
    role: 'Research Fellow',
    institutionType: 'Russell Group University',
    discipline: 'Electronic Engineering',
    region: 'Wales',
    timeWindow: '1–6 months ago',
    whatHappened: 'A safety officer identified that a signed acknowledgement page from the laser safety logbook had not been returned to the department office. No written notice was issued. The equipment owner was not informed at any point before, during, or after the intervention. Three physical actions were carried out on the same day without any communication: the mains power cable to the laser system was cut, the wall-mounted safety interlock panel was removed entirely, and the laser housing was secured with a padlock. At least two other laboratories operating class 3B and class 4 laser systems received no equivalent action despite comparable administrative circumstances.',
    impact: 'The laser system was offline for eleven working days. A time-sensitive characterisation study was delayed and a co-authored manuscript submission was postponed. The complete absence of prior communication meant irreversible physical damage was done to resolve a simple administrative matter.',
    improvement: 'No physical intervention on research equipment should take place without prior written notification to the equipment owner. Safety non-compliance should follow a graduated process: written notice, then dialogue, then proportionate escalation only if unresolved.',
    consentPublish: true,
    publishTitle: 'Triple-Lock Shutdown With No Notice to Equipment Owner: Cable Cut, Panel Removed, System Padlocked',
    publishSummary: 'A researcher\'s laser system was physically shut down through three simultaneous interventions — including a cut power cable — with no written notice issued and the equipment owner not informed at any stage, while neighbouring labs with equivalent systems were left untouched.',
    publishStory: '### What happened\nA safety officer identified an outstanding administrative item: a signed acknowledgement from a laser safety logbook had not been returned. No written notification was issued and the equipment owner was not informed at any point. Without any prior communication, three physical actions were carried out on the same day: the mains power cable to the laser system was cut, the wall-mounted safety interlock panel was removed entirely, and the laser housing was secured with a padlock. At least two other laboratories with comparable systems had no equivalent action taken.\n\n### Impact\nThe laser system was offline for eleven working days. A funded characterisation study was delayed and a co-authored manuscript submission was postponed. The researcher felt unable to raise the incident formally due to concern about further disproportionate response.\n\n### What would help\nNo physical intervention on research equipment should proceed without prior written notification to the equipment owner. Safety non-compliance should be managed through a graduated process: written notice first, then dialogue, then proportionate escalation only if unresolved.',
    anonymisationNotes: JSON.stringify(['Laser class described generically', 'Building and department location removed']),
    riskFlags: JSON.stringify(['Possible differential enforcement — comparable labs not treated equivalently']),
    confidence: 'high',
    publishedAt: new Date(Date.now() - 86400000 * 50),
  },
  {
    id: 'seed-3',
    createdAt: new Date(Date.now() - 86400000 * 45),
    status: 'published',
    role: 'PhD Student',
    institutionType: 'Russell Group University',
    discipline: 'Chemistry',
    region: 'West Midlands',
    timeWindow: '6–12 months ago',
    whatHappened: 'A routine annual safety inspection was being carried out on our floor. Without any advance notice, an inspector switched off the main extract control for our fume hoods as part of a test. At that moment I had an active reflux running inside one of them — a multi-step synthesis I had been building towards for six weeks. The fume hood fan stopping caused the temperature inside to rise and the reaction atmosphere to change. By the time I noticed and understood what was happening, the reaction had progressed to a point I could not safely reverse. The batch was lost.',
    impact: 'Six weeks of synthesis work was lost in under twenty minutes. The chemicals consumed had an estimated replacement cost of several hundred pounds. I had to restart from an earlier intermediate, adding approximately three weeks to my timeline.',
    improvement: 'Inspectors testing live ventilation systems in working laboratories must confirm that no active experiments are running before conducting tests that interrupt airflow.',
    consentPublish: true,
    publishTitle: 'Unannounced Fume Hood Test Destroys Six Weeks of Synthesis Work',
    publishSummary: 'A safety inspector cut extract power to a laboratory fume hood during a routine test without checking whether active experiments were running, resulting in the loss of a six-week chemical synthesis.',
    publishStory: '### What happened\nDuring a routine safety inspection, an inspector disabled the extract ventilation system serving a laboratory\'s fume hoods as part of a live airflow test. No notification had been given to the researchers. A researcher had an active multi-step synthesis running under reflux inside one of the affected fume hoods at the time. The loss of airflow caused a change in reaction conditions. By the time the researcher identified the cause, the synthesis had been irreversibly compromised.\n\n### Impact\nSix weeks of preparatory synthesis work was lost. Restarting from an earlier intermediate added an estimated three weeks to the researcher\'s experimental programme.\n\n### What would help\nInspectors conducting live tests on building systems in active research spaces must confirm that no time-sensitive or hazardous processes are in progress before proceeding.',
    anonymisationNotes: JSON.stringify(['Specific reaction chemistry removed', 'Floor and building location removed']),
    riskFlags: JSON.stringify([]),
    confidence: 'high',
    publishedAt: new Date(Date.now() - 86400000 * 41),
  },
  {
    id: 'seed-4',
    createdAt: new Date(Date.now() - 86400000 * 36),
    status: 'published',
    role: 'PhD Student',
    institutionType: 'Post-92 University',
    discipline: 'Biology / Life Sciences',
    region: 'Scotland',
    timeWindow: '1–6 months ago',
    whatHappened: 'I was sitting in the data analysis bay adjacent to our wet laboratory — a separate write-up area with no chemical or biological hazards — when a safety officer entered and, in a loud voice in front of four colleagues and two visiting students, informed me I was in violation of PPE policy for not wearing safety glasses. I explained I was in the write-up area, not the laboratory. They issued me a formal written warning on the spot. The same officer regularly passes through the main wet lab area without comment when the principal investigator — a full professor — is working without eye protection.',
    impact: 'The public nature of the interaction was deeply humiliating. I felt singled out in front of peers and visitors. The incident affected my confidence for several weeks and created low-level resentment in our group towards safety policies implementation or enforcement.',
    improvement: 'PPE enforcement should be consistent regardless of seniority. Formal warnings should not be issued as a first response — a quiet, private conversation is always preferable where there is no immediate danger.',
    consentPublish: true,
    publishTitle: 'Public PPE Reprimand in Write-Up Area; Senior Staff Ignored',
    publishSummary: 'A first-year PhD student received a formal public warning for not wearing safety glasses in a designated write-up area, while the same officer repeatedly overlooked identical behaviour from a senior professor in the adjacent wet laboratory.',
    publishStory: '### What happened\nA researcher working in a designated write-up area was publicly challenged by a safety officer for not wearing safety eye protection and issued a formal written warning on the spot. The researcher had not entered the laboratory space. The same safety officer was observed on multiple occasions passing through the active wet laboratory without comment when a senior academic was present without eye protection.\n\n### Impact\nThe public nature of the interaction caused significant distress to the researcher, who was in the early stage of their doctoral programme. The perceived inconsistency in enforcement generated resentment and undermined the credibility of safety governance.\n\n### What would help\nPPE policy must be applied consistently and without regard to seniority. Formal warnings should never be a first response in the absence of immediate risk.',
    anonymisationNotes: JSON.stringify(['Institution and department removed', 'Seniority described generically']),
    riskFlags: JSON.stringify(['Possible differential enforcement by seniority']),
    confidence: 'high',
    publishedAt: new Date(Date.now() - 86400000 * 32),
  },
  {
    id: 'seed-5',
    createdAt: new Date(Date.now() - 86400000 * 28),
    status: 'published',
    role: 'Technical Staff / Technician',
    institutionType: 'Russell Group University',
    discipline: 'Chemistry',
    region: 'North West',
    timeWindow: '6–12 months ago',
    whatHappened: 'A safety officer identified what they described as a potential electrical fault near the shared NMR spectrometer. Without contacting the instrument manager or any of the research groups with active samples, they powered down the machine completely. The fault turned out to be a cable tie that had melted slightly against a warm surface — a cosmetic issue with no functional risk. The spectrometer remained offline for nine days. During this time, samples from four research groups — including two containing biomaterials collected from clinical donors — were lost.',
    impact: 'The loss of clinically sourced samples was irreversible. Two groups had to formally notify their ethics committees. The instrument manager, who was available and contactable at the time, was not consulted before the shutdown.',
    improvement: 'Decisions to shut down specialist shared research infrastructure must require consultation with a named instrument manager before any action is taken. Proportionality must be built into the decision-making process.',
    consentPublish: true,
    publishTitle: 'Unilateral NMR Shutdown Over Cable Tie Causes Loss of Clinical Samples',
    publishSummary: 'A safety officer powered down a shared NMR spectrometer without consulting the instrument manager, citing a minor surface marking on a cable tie. Nine days of downtime led to the irreversible loss of clinically donated samples across four research groups.',
    publishStory: '### What happened\nA safety officer identified a superficial marking on a cable tie near shared analytical instrumentation and classified it as a potential electrical fault. Without informing the instrument manager or any of the affected research groups, the instrument was powered down immediately. The cause was subsequently confirmed to be cosmetic and non-functional. The instrument remained offline for nine days pending a formal assessment. During this period, samples from multiple research groups — including irreplaceable materials from clinical donors — were lost.\n\n### Impact\nThe loss of clinically sourced samples was permanent and required formal notification to the relevant ethics committees. The instrument manager, available and contactable at the time, was not consulted.\n\n### What would help\nShutdown decisions for specialist shared infrastructure must require documented consultation with a named technical lead before action is taken, except in cases of immediate and serious danger.',
    anonymisationNotes: JSON.stringify(['Department and building removed', 'Clinical nature of samples retained as central to impact']),
    riskFlags: JSON.stringify(['Loss of ethically approved clinical samples — may require separate institutional review']),
    confidence: 'high',
    publishedAt: new Date(Date.now() - 86400000 * 24),
  },
  {
    id: 'seed-6',
    createdAt: new Date(Date.now() - 86400000 * 19),
    status: 'published',
    role: 'PhD Student',
    institutionType: 'Post-92 University',
    discipline: 'Engineering',
    region: 'Yorkshire and the Humber',
    timeWindow: '1–6 months ago',
    whatHappened: 'I identified a faulty gas line connector in our workshop and submitted a formal near-miss report through the departmental online system. Within 48 hours of submitting the report, my access card was deactivated. I received a brief automated email stating my access was "suspended pending a safety review." No one contacted me to explain what the review involved or how long it would take. I heard nothing for six weeks. Other students and staff who had not submitted reports continued to access the workshop throughout.',
    impact: 'The six-week suspension halted my experimental programme during a critical phase. My annual review had to be deferred. The experience made me deeply reluctant to submit any future safety reports. Several peers said they would not report a safety issue as a result.',
    improvement: 'Near-miss reporting must not result in access suspension for the reporter without clear, documented justification and immediate personal communication. The process must be transparent and not feel punitive.',
    consentPublish: true,
    publishTitle: 'Near-Miss Report Filed; Lab Access Suspended 48 Hours Later',
    publishSummary: 'A researcher who submitted a formal near-miss safety report lost workshop access within two days, with no explanation provided for six weeks. The experience deterred others in the research group from reporting safety concerns.',
    publishStory: '### What happened\nA researcher identified a potentially hazardous fault in shared workshop equipment and submitted a formal near-miss report. Within 48 hours, their building access was suspended with a brief automated notification. No further communication was received for six weeks. Other members of the group retained full access throughout.\n\n### Impact\nThe suspension coincided with a critical phase of the researcher\'s experimental programme and required deferral of a scheduled annual progress review. Several peers stated they would not report safety concerns either.\n\n### What would help\nSubmitting a safety report must not result in access suspension without explicit documented justification and immediate personal communication. Institutions should audit whether safety reporting correlates with any form of access restriction.',
    anonymisationNotes: JSON.stringify(['Equipment type described generically', 'Department and building removed']),
    riskFlags: JSON.stringify(['Possible retaliatory response to safety reporting — EDI and whistleblowing policy implications']),
    confidence: 'high',
    publishedAt: new Date(Date.now() - 86400000 * 15),
  },
  {
    id: 'seed-7',
    createdAt: new Date(Date.now() - 86400000 * 10),
    status: 'published',
    role: 'Research Fellow',
    institutionType: 'Independent Research Institute',
    discipline: 'Materials Science',
    region: 'East Midlands',
    timeWindow: '1–3 years ago',
    whatHappened: 'A label on a secondary chemical container in my storage area had faded — the chemical name was still readable but the hazard pictograms had degraded. I acknowledged this when flagged during an inspection and offered to replace the label the same day. Instead, the safety officer escalated to my line manager and the departmental safety committee. The outcome was a requirement that I attend the Level 1 laboratory induction course — a half-day session designed for first-year undergraduates. I have fifteen years of laboratory experience and was supervising two PhD students. Several of my students were present in the session.',
    impact: 'The professional humiliation of attending a first-year induction in a room of students I supervised was significant and lasting. My confidence in engaging with the safety management system was severely damaged. I began to self-censor any acknowledgement of minor non-compliance in subsequent inspections.',
    improvement: 'Remediation for minor administrative non-compliance should be proportionate and private. Mandatory attendance at introductory training designed for complete novices should never be used as a disciplinary measure for experienced professionals.',
    consentPublish: true,
    publishTitle: 'Senior Researcher Required to Attend First-Year Induction Over Faded Label',
    publishSummary: 'A research fellow with fifteen years of laboratory experience was required to attend a Level 1 undergraduate induction course — alongside students they supervised — after a chemical container label had faded during storage.',
    publishStory: '### What happened\nDuring a routine inspection, a safety officer identified a secondary chemical container whose hazard label had degraded — pictograms were partially illegible though the chemical name remained readable. The researcher acknowledged the issue and offered to replace the label immediately. Rather than accepting this, the officer escalated to line management. The resulting action required the researcher — a postdoctoral-level professional with fifteen years of experience — to attend a Level 1 laboratory induction session designed for first-year undergraduates. Some of those present were supervised by the researcher.\n\n### Impact\nThe researcher experienced a significant and enduring loss of professional standing. Their willingness to acknowledge minor non-compliance in future inspections was severely reduced.\n\n### What would help\nRemediation for minor administrative non-compliance must be proportionate. A private conversation or written reminder is appropriate in almost all such cases. Mandatory participation in introductory training designed for novices should not be deployed as a corrective measure for experienced professionals.',
    anonymisationNotes: JSON.stringify(['Institution type generalised', 'Country references removed', 'Professional qualification type removed']),
    riskFlags: JSON.stringify([]),
    confidence: 'high',
    publishedAt: new Date(Date.now() - 86400000 * 6),
  },
];

export async function seedIfEmpty(db: typeof pool): Promise<void> {
  const { rows } = await db.query('SELECT COUNT(*) AS count FROM submissions');
  if (parseInt(rows[0].count, 10) > 0) return;

  console.log('[seed] Table is empty — inserting seed records…');
  for (const s of seeds) {
    await db.query(
      `INSERT INTO submissions (
        id, created_at, status, role, institution_type, region, discipline, time_window,
        what_happened, impact, improvement, consent_publish,
        publish_title, publish_summary, publish_story,
        anonymisation_notes, risk_flags, confidence, published_at
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
      ON CONFLICT (id) DO NOTHING`,
      [
        s.id, s.createdAt, s.status, s.role, s.institutionType, s.region, s.discipline, s.timeWindow,
        s.whatHappened, s.impact, s.improvement, s.consentPublish,
        s.publishTitle, s.publishSummary, s.publishStory,
        s.anonymisationNotes, s.riskFlags, s.confidence, s.publishedAt,
      ]
    );
  }
  console.log(`[seed] Inserted ${seeds.length} seed records.`);
}
